config/routes.rb
Rails.application.routes.draw do
  get "users/new"
  get "users/create"
  devise_for :users, controllers: {
    registrations: 'registrations',
    sessions: 'sessions'
  }

  devise_scope :user do
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"

  resources :subscriptions, only: [:index, :new, :create]
  resources :users, only: [:new, :create]
  resources :dashboard, only: [:index]
  resources :chat, only: [:show, :create]
  resources :emoti, only: [:index] do
    collection do
      get 'selection'
    end
  end
  resources :emoti_questions, only: [:index] do
    collection do
      post 'choose_emoti'
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
    @emotis ||= helpers.load_current_user_emotis
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.haml
%section.section.dashboard-container{data: { controller: "dashboard" }}
  .welcome-info
    .welcome-info-wrapper
      = link_to chat_path('last') do
        = image_tag 'emotis/emoti.png', alt: 'emoti'
      .welcome-info-text
        %p
  %section.section.user-info.has-text-centered
    .subscription-info
      - if current_user.active_subscription.present?
        %p.title.is-4.is-flex.is-align-items-center.is-justify-content-center
          = I18n.t('subscription.your_plan')
          %span.tag.is-success.ml-2= I18n.t('subscription.active')
        %p= I18n.t('dashboard.fecha_expiracion', date: current_user.active_subscription.until.strftime("%d/%m/%Y"))
        %p.expiry= I18n.t('dashboard.fecha_expiracion', date: current_user.active_subscription.until.strftime("%d/%m/%Y"))
        %p.days-left= "Días restantes: #{(current_user.active_subscription.until - Date.today).to_i}"
        = link_to I18n.t('subscription.upgrade'), 'subscriptions_path', class: "button is-success"
      - else
        %p.title.is-4
          = I18n.t('subscription.your_plan')
          %span.tag.is-danger= I18n.t('subscription.inactive')
        = link_to I18n.t('subscription.renew'), 'subscriptions_path', class: "renew-link"

  %section.section
    = render partial: 'emoti/emoti_carousel'