config/routes.rb
Rails.application.routes.draw do
  get "users/new"
  get "users/create"
  devise_for :users, controllers: {
    registrations: 'registrations',
    sessions: 'sessions'
  }

  devise_scope :user do
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"

  resources :subscriptions, only: [:index, :new, :create]
  resources :users, only: [:new, :create]
  resources :dashboard, only: [:index]
  resources :chat, only: [:show, :create]
  resources :emoti, only: [:index] do
    collection do
      get 'selection'
    end
  end
  resources :emoti_questions, only: [:index] do
    collection do
      post 'choose_emoti'
    end
  end
end

app/models/emoti.rb
class Emoti
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :chats

  field :name, type: String
  field :title, type: String
  field :quote, type: String
  field :description, type: String
  field :prompt, type: String
  field :key, type: String
  field :initial_message, type: String, default: 'emoti.initial_message'
  field :active, type: Boolean, default: true

  validates_uniqueness_of :key

  scope :actives, -> { where(active: true) }

end

app/controllers/emoti_controller.rb
class EmotiController < ApplicationController

  def index
    helpers.load_current_user_emotis
  end

  def selection
    @emotis = Emoti.actives
  end
end

app/helpers/emoti_helper.rb
module EmotiHelper
end

app/views/emoti/_emoti_carousel.html.haml
.emoti-container{data: { controller: "emoti" }}
  %section.emotis-section
    .emotis-glide
      = content_tag :div, data: { glide_el: "track" }, class: "glide__track" do
        = content_tag :ul, class: "glide__slides" do
          - @emotis.each do |emoti|
            = content_tag :li, class: "glide__slide" do
              .card
                .card-image
                  .image.is-1by1
                    =image_tag "emotis/#{emoti.key}.png"
                .card-content
                  .media
                    .media-content
                      %p.title.is-4= emoti.name
                      %p.subtitle.is-6= emoti.quote
                  .content
                    %a{href: chat_path(emoti.id)} HABLAR

app/views/emoti/index.html.haml
= render partial: 'emoti/emoti_carousel'

app/views/emoti/selection.html.haml
.selection-container
  .find-your-emoti-container
    = link_to I18n.t('find_your_emoti'), emoti_questions_path

  = render partial: 'emoti/emoti_carousel'