config/routes.rb
Rails.application.routes.draw do
  get "users/new"
  get "users/create"
  devise_for :users, controllers: {
    registrations: 'registrations',
    sessions: 'sessions'
  }

  devise_scope :user do
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"

  resources :subscriptions, only: [:index, :new, :create]
  resources :users, only: [:new, :create]
  resources :dashboard, only: [:index]
  resources :chat, only: [:show, :create]
  resources :emoti, only: [:index] do
    collection do
      get 'selection'
    end
  end
  resources :emoti_questions, only: [:index] do
    collection do
      post 'choose_emoti'
    end
  end
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title= content_for(:title) || I18n.t('sena')
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}
    %meta{:content => "yes", :name => "mobile-web-app-capable"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    %meta{"http-equiv" => "X-UA-Compatible", content: "IE=edge"}
    %meta{name: "format-detection", content: "telephone=no"}
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{:href => "/icon.png", :rel => "icon", :type => "image/png"}
    %link{:href => "/icon.svg", :rel => "icon", :type => "image/svg+xml"}
    %link{:href => "/icon.png", :rel => "apple-touch-icon"}
    = tag.link rel: 'manifest', href: pwa_manifest_path(format: :json)
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = javascript_importmap_tags
    %link{rel: "preconnect", href: "https://fonts.googleapis.com"}
    %link{rel: "preconnect", href: "https://fonts.gstatic.com", crossorigin: true}
    %link{rel: 'stylesheet', href: 'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,200..800;1,200..800&display=swap'}
    %link{rel: 'stylesheet', href: 'https://cdnjs.cloudflare.com/ajax/libs/Glide.js/3.6.0/css/glide.core.min.css'}
    %link{rel: 'stylesheet', href: 'https://cdnjs.cloudflare.com/ajax/libs/Glide.js/3.6.0/css/glide.theme.min.css'}
    %link{rel: "stylesheet", href: "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"}

  %body
    .container
      = render 'components/header'
      = yield
    %script{src: 'https://cdnjs.cloudflare.com/ajax/libs/Glide.js/3.6.0/glide.min.js'}
    %script{src: 'https://unpkg.com/typewriter-effect@latest/dist/core.js'}